[[buildpacks]]
  uri = "../node-bins/"
  version = "0.0.2"

[[buildpacks]]
  uri = "../node-install/"
  version = "0.0.1"

[[order]]

[[order.group]]
id = "atgracey/node-bins"
version = "0.0.2"

[[order.group]]
id = "atgracey/node-install"
version = "0.0.1"


# Stack that will be used by the builder
[stack]
id = "opensuse.stack.leap15.3"
run-image = "registry.opensuse.org/home/atgracey/opensuse_leap_15.3/cnbp_run:latest"
build-image = "docker.io/atgracey/metabuildpackbuild:latest"
