[[buildpacks]]
  uri = "../node-bins/"
  version = "0.0.2"

[[buildpacks]]
  uri = "../node-install/"
  version = "0.0.1"

[[order]]

[[order.group]]
id = "atgracey/node-bins"
version = "0.0.2"

[[order.group]]
id = "atgracey/node-install"
version = "0.0.1"


# Stack that will be used by the builder
[stack]
id = "atgracey.stack.test"
run-image = "docker.io/atgracey/testbprun:latest"
build-image = "docker.io/atgracey/testbpbuild:latest"
