[[buildpacks]]
  uri = "../node-bins/"
  version = "0.0.2"

[[buildpacks]]
  uri = "../node-install/"
  version = "0.0.1"

[[order]]

[[order.group]]
id = "atgracey/node-bins"
version = "0.0.2"

[[order.group]]
id = "atgracey/node-install"
version = "0.0.1"


# Stack that will be used by the builder
[stack]
id = "sle.stack.15.4"
run-image = "registry.opensuse.org/home/atgracey/cnbp/containers/cnbp_run:latest"
build-image = "registry.opensuse.org/home/atgracey/cnbp/containers/cnbp_build:latest"
